name: Accept ADRs

on:
  push:
    branches: [main]
    paths: ["doc/adr/**"]

jobs:
  accept_adrs:
    name: Accept ADRs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - uses: jackdar/adr-action@v1
