name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Tag and Release
        uses: ./.github/actions/release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
